version: "3"
services:
  redis:
    image: redis/redis-stack-server:7.2.0-v6
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    volumes:
      - redis_data:/data
    networks:
        - blab_network

  blab_backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
        - REDIS_URL=redis:6379
    depends_on:
      - redis
    restart: always
    networks:
      - blab_network

volumes:
  redis_data:

networks:
  blab_network:

